spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 2
#      idle-timeout: 30000
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tmp
    username: postgres
    password: testdb
  data:
    web:
      pageable:
        one-indexed-parameters: true
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create-drop

  jimmer:
    foreign-key-enabled-by-default: false
    default-enum-strategy: name
    log:
      enable: true
      kind: default
      pretty: true
      inline-sql-variables: true
      name: "jimmer.dml.sql"
    ddl-auto: update
    database-naming-strategy: lower_case
