spring:
  cache:
    redis:
      time-to-live: 120s
      key-prefix: "i:spring:test"
  data:
    redis:
      database: 0
      host: 10.37.1.132
      port: 6379
#      cluster:
#        nodes: 10.37.1.133:6001,10.37.1.133:6002,10.37.1.133:6003,10.37.1.133:6004,10.37.1.133:6005,10.37.1.133:6006
      password: 123456
      timeout: 5000
i:
  spring:
    cache:
      redis:
        enabled-event: true
