spring:
  cache:
    redis:
      time-to-live: 120s
      key-prefix: "i:spring:test"
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
#      cluster:
#        nodes: 127.0.0.1:6001,127.0.0.1:6002,127.0.0.1:6003,127.0.0.1:6004,127.0.0.1:6005,127.0.0.1:6006
      password: 123456
      timeout: 5000
i:
  spring:
    cache:
      redis:
        enabled-event: true
